title: Bodrum Property Group
description: Creative Property Investment - Manchester
url: "https://carltracy.github.io"
baseurl: "/bodrum-property-group"

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
